version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8888:8080
      - 7077:7077
    volumes: 
      - ./master-volumes/logs:/opt/spark/logs
      - ./shared-workspace:/opt/workspace
  
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  jupyterlab:
    image: jupyter-lab
    container_name: jupyter-lab
    ports:
      - 9999:9999
    volumes:
      - ./shared-workspace:/opt/workspace